# Site
name: 'L.E.O'
description: 'The literary club of Sir M. Visvesvaraya Institute of Technology, Bangalore.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl:
disqus: 'leomvit'
email: 'contacts.leomvit@gmail.com'
mailchimp-list: 'http://eepurl.com/gB-qZf'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:

  abhishek:
    name:           Abhishek Kumar
    avatar:         "assets/images/authors/abhishek.jpg"
    bio:            "Exploring darkness to embrace light. Exploring words to embrace life. A growing engineer trying to figure out life through words."
    email:          abhiabhikr7@gmail.com
    twitter:        https://www.instagram.com/abhishekk_kumarr__/

adarsh:
    name:           Adarsh Singh
    #site:          https://www.linkedin.com/in/adarsh-singh-7b9a98201/
    avatar:         "assets/images/authors/adarsh.jpeg"
    bio:            "A cheerful tech enthusiast (weird, isn't it?). I can do things which no one can and no one can do things which I can!"
    email:          adarshsingh22032002@gmail.com
    twitter:        https://www.instagram.com/just_adarsh22/

  adkgup:
    name:           Adarsh Kumar Gupta
    site:           https://adkgup.live/
    avatar:         "assets/images/authors/adkgup.jpg"
    bio:            "I don't have the strength to keep writing this."
    email:          adarshkgupta@outlook.com
    twitter:        https://www.instagram.com/adkgup/

  avikant:
    name:           Avikant Srivastava
    #site:           http://avikant.works/
    avatar:         "assets/images/authors/avikant.jpeg"
    bio:            "A Technophile, Geek and part time Poet. Loves Music, Skateboards and Formula 1"
    email:          asdavikant@gmail.com
    twitter:        https://www.instagram.com/aesthetixell

  deeksha:
    name:           Deeksha
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/deeksha.jpeg"
    bio:            "Words let me speak."
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/deeksha_ramesh15/

  kaushiki:
    name:           Kaushiki Krity
    avatar:         "assets/images/authors/kaushiki.jpeg"
    bio:            "Weird from a normal point of view and normal from a weird point of view."
    email:          kaushikiworks@gmail.com
    twitter:        https://www.instagram.com/_kauzzkayy_/

  kushagra:
    name:           Kushagra Agarwal
    site:           https://codewithkushagra.netlify.app/
    avatar:         "assets/images/authors/kushagra.jpg"
    bio:            "I am a code geek, a NARUTO fan and also love expressing my depression in words :)"
    email:          kushagraagra008@gmail.com
    twitter:        https://www.instagram.com/kushagra_agra008/

  masoomi:
    name:           Masoomi Saxena
    # site:         https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/masoomi.jpg"
    bio:            "A bibliophile ambivert with great passion for chicken nuggets. Find me blabbering on stage or jamming to Lana Del Rey."
    email:          masoomi.saxena99@gmail.com
    twitter:        https://www.instagram.com/masyoyummy/

  pratyush:
    name:           Pratyush Kumar Shekhar
    site:           https://thesoulmeltingwords.blogspot.com/
    avatar:         "assets/images/authors/pratyush.jpeg"
    bio:            "Turned my dreams into my vision and my vision into my reality."
    email:          shekharofficial311@gmail.com
    twitter:        https://www.instagram.com/_shekhar_official_/

  satyam:
    name:           Satyam Shree
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/satyam.jpeg"
    bio:            "I'll let my poems speak for me."
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/satyam_shree_cookie_s22/

  shivani:
    name:           Shivani Sen
    site:           http://unlockingdoor.blogspot.com/
    avatar:         "assets/images/authors/shivani.jpeg"
    bio:            "A budding engineer, aspires to make people feel experiences with her words."
    email:          shivani.sen16052000@gmail.com
    twitter:        https://www.instagram.com/ssshhh_vani/

  shreoshee:
    name:           Shreoshee Mukherjee
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/shreoshee.jpeg"
    bio:            "A dreamer, who just graduated to real life. Loves to be herself. Can't resist pets. Aims to be a Talky and a Techie person. ðŸ™ˆ"
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/shreoshee_mukherjee/

  shubhani:
    name:           Shubhani Mulay
    avatar:         "assets/images/authors/shubhani.jpg"
    bio:            "A budding engineer and a newbie writer!"
    email:          shubhani.mulay25@gmail.com
    twitter:        https://www.instagram.com/mulay_shubhani25/

  shubhra:
    name:           Shubhra Dixit
    avatar:         "assets/images/authors/shubhra1.jpeg"
    bio:            "Writing to calm my soul. Probably listening to an indie artist on repeat.The unknown fascinates me."
    email:          dixitshubhra73@gmail.com
    twitter:        https://www.instagram.com/_lostnow_/

  swati:
    name:           Swati Mishra
    site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/swati.png"
    bio:            "A proud misfit who's all about dogs, books and everything that's Bollywood. Still waiting for a Hogwarts letter."
    email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/winged_pursuits

  vedang:
    name:           Vedang Singh Thakur
    avatar:         "assets/images/authors/vedang.jpeg"
    bio:            "Small town boy trying to make stuff happen."
    email:          vst0010@gmail.com
    twitter:        https://www.instagram.com/vst_10/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
