# Site
name: 'L.E.O'
description: 'The literary club of Sir M. Visvesvaraya Institute of Technology, Bangalore.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl:
disqus: 'leomvit'
email: 'contacts.leomvit@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  shivani:
    name:           Shivani Sen
    site:           http://unlockingdoor.blogspot.com/
    avatar:         "assets/images/authors/shivani.jpeg"
    bio:            "A budding engineer, aspires to make people feel experiences with her words."
    email:          shivani.sen16052000@gmail.com
    twitter:        https://www.instagram.com/ssshhh_vani/

  satyam:
    name:           Satyam Shree
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/satyam.jpeg"
    bio:            "A proud misfit who's all about dogs, books and everything that's Bollywood. Still waiting for a Hogwarts letter."
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/satyam_shree_cookie_s22/

  swati:
    name:           Swati Mishra
    site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/swati.png"
    bio:            "A proud misfit who's all about dogs, books and everything that's Bollywood. Still waiting for a Hogwarts letter."
    email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/winged_pursuits/

  abhishek:
    name:           Abhishek Kumar
    avatar:         "assets/images/authors/abhishek.jpg"
    bio:            "Exploring darkness to embrace light. Exploring words to embrace life. A growing engineer trying to figure out life through words."
    email:          abhiabhikr7@gmail.com
    twitter:        https://www.instagram.com/abhishekk_kumarr__/

  vedang:
    name:           Vedang Singh Thakur
    avatar:         "assets/images/authors/vedang.jpeg"
    bio:            "Small town boy trying to make stuff happen."
    email:          vst0010@gmail.com
    twitter:        https://www.instagram.com/vst_10/

  deeksha:
    name:           Deeksha
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/deeksha.jpeg"
    bio:            "Words let me speak."
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/deeksha_ramesh15/

  shreoshree:
    name:           Shreoshree
    # site:           https://swati1995blog.wordpress.com/
    avatar:         "assets/images/authors/shreoshree.jpeg"
    bio:            "A Dreamer....Who just graduated to realife. Loves to be herself. Cant resist pets. Aims to be a Talky and a Techie personðŸ™ˆ"
    # email:          fakemail@gmail.com
    twitter:        https://www.instagram.com/shreoshee_mukherjee/


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
